name: Deploy to Google Cloud

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Configure gcloud
      run: |
        gcloud config set project photocloud-443915
        gcloud config set compute/region us-central1

    # Step 4: Build and push the Docker image
    - name: Build and push Docker image
      run: |
        IMAGE_NAME="gcr.io/photocloud-443915/test-image"
        docker build -t test-image .
        docker push test-image

    # Step 5: Deploy to Google Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy photocloudapp \
          --image gcr.io/photocloud-443915/test-image \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
