name: Deploy to Google Cloud

on:
  push:
    branches:
      - main # Trigger on push to the main branch
      - gha

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: |
          {
            "type": "service_account",
            "project_id": "${{ secrets.PID }}",
            "private_key_id": "${{ secrets.PKEYID }}",
            "private_key": "${{ secrets.PKEY }}",
            "client_email": "${{ secrets.CEMAIL }}",
            "client_id": "${{ secrets.CID }}",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/${{ secrets.URL }}",
            "universe_domain": "googleapis.com"
          }

    - name: Create Google Credentials JSON (for key security)
      run: |
        echo '{
          "type": "service_account",
          "project_id": "${{ secrets.PID }}",
          "private_key_id": "${{ secrets.PKEYID }}",
          "private_key": "${{ secrets.PKEY }}",
          "client_email": "${{ secrets.CEMAIL }}",
          "client_id": "${{ secrets.CID }}",
          "auth_uri": "https://accounts.google.com/o/oauth2/auth",
          "token_uri": "https://oauth2.googleapis.com/token",
          "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
          "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/${{ secrets.URL }}",
          "universe_domain": "googleapis.com"
        }' > credentials.json

    - name: debug
      run: cat credentials.json

    - name: Configure gcloud
      run: |
        gcloud config set project photocloud-443915
        gcloud config set compute/region us-central1
        gcloud auth configure-docker gcr.io --quiet

#    - name: Build and push Docker image
#      uses: docker/build-push-action@v6
#      with:
#        context: ./
#        file: ./Dockerfile
#        push: true
#        tags: docker.io/lleftyy/photocloudapp:latest
#      env:
#        GOOGLE_APPLICATION_CREDENTIALS_CONTENT: $(pwd)/credentials.json

    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: lleftyy/photocloudapp:latest

    - name: Deploy Image Processing to Cloud Functions
      run: |
        gcloud functions deploy upload_image \
          --runtime python310 \
          --trigger-http \
          --allow-unauthenticated \
          --source upload_image

    - name: Deploy Application to Cloud Run
      run: |
        gcloud run deploy photocloudapp \
          --image docker.io/lleftyy/photocloudapp:latest \
          --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=credentials.json \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --timeout 600s
